### ISSUE TITLE
malloc(): invalid size (unsorted)

### ISSUE THREAD

**Issue by xiyaowong** [Cubified/colorslide#1]
![image](https://user-images.githubusercontent.com/47070852/176387458-7004371c-b312-4f24-a585-295048311d0e.png)

**Comment by Cubified** [comment]
Hi @xiyaowong, thanks for opening this.  I think I've fixed the issue with my latest few commits, could you give it another try?

**Comment by xiyaowong** [comment]
@Cubified  fixed. but a new problem occurred
![image](https://user-images.githubusercontent.com/47070852/176570352-73980064-b8d6-4fb8-9834-9c3fc8060b1f.png)
no color

**Comment by Cubified** [comment]
Okay it should all be fixed now, originally the color would hide if the terminal window was too small but I changed it to show at a reduced size.

**Comment by xiyaowong** [comment]
thx
